name: ci
on:
    pull_request:
        branches:
          - master
          - develop
    push:
        branches:
          - master
          - develop
jobs:
    python-poetry:
        runs-on: ubuntu-20.04
        strategy:
          fail-fast: false
          matrix:
            python-version: ['3.8']
        steps:
            - uses: actions/checkout@v2
            - name: Install poetry
              run: pip install poetry
            - name: Install develop dependencies
              run: poentry
            - name: Running flake8
              run: poetry run python -m flake8
            - name: Running tests
              run: poetry run python -m pytest
