name: ci
on:
    pull_request:
        branches:
          - master
          - develop
    push:
        branches:
          - master
          - develop
jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
          fail-fast: false
          matrix:
            python-version: ['3.8']
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install poetry
              run: |
                pip install poetry
                echo "$HOME/.local/bin" >>$GITHUB_PATH
                export PATH="$HOME/.local/bin:$PATH"
            - name: Install develop dependencies
              run: poentry
            - name: Running flake8
              run: poetry run python -m flake8
            - name: Running tests
              run: poetry run python -m pytest
