name: ci
on:
    pull_request:
        branches:
          - master
          - develop
    push:
        branches:
          - master
          - develop
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Install poetry
              run: pipx install poetry
            - name: Setup Python
              uses: ./
              with:
                python-version: 3.8
                cache: 'poetry'
            - name: Install develop dependencies
              run: poentry
            - name: Running flake8
              run: poetry run python -m flake8
            - name: Running tests
              run: poetry run python -m pytest
