name: ci
on:
    pull_request:
        branches:
          - master
          - develop
    push:
        branches:
          - master
          - develop
jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                python-version: ['3.8']
                poetry-version: ['1.1.8']
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - uses: snok/install-poetry@v1
              with:
                virtualenvs-create: true
                virtualenvs-in-project: true
                installer-parallel: true

            - name: Install develop dependencies
              run: |
                python -m poentry install
            - name: Running autotests
              run: |
                python -m pytest
