name: ci
on:
    pull_request:
        branches:
          - master
          - develop
    push:
        branches:
          - master
          - develop
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install poetry
              run: |
                "$HOME/.local/bin" >> $GITHUB_PATH
                pip install poetry

            - name: Install develop dependencies
              run: |
                poentry install
            - name: Running flake8
              run: |
                poetry run python -m flake8
            - name: Running tests
              run: |
                poetry run python -m pytest
