name: ci
on:
    pull_request:
        branches:
          - master
          - develop
    push:
        branches:
          - master
          - develop
jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
          fail-fast: false
          matrix:
            python-version: ['3.8']
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install and configure Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.1.10
                virtualenvs-create: true
                virtualenvs-in-project: false
                virtualenvs-path: ~/my-custom-path
                installer-parallel: true
            - name: Running flake8
              run: poetry run flake8
            - name: Running tests
              run: poetry run pytest
